spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  h2:
    console:
      enabled: true

  datasource:
    core:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:core;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      pool-name: core-db-pool

  cloud.openfeign:
    client:
      config:
        default:
          logger-level: full
    compression:
      response:
        enabled: false
    httpclient:
      max-connections: 2000
      max-connections-per-route: 500

oauth:
  google:
    client-id: ${OAUTH_GOOGLE_CLIENT_ID:oauth.google.client-id}
    client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:oauth.google.client-secret}
    scope: profile, email

  x:
    client-id: ${OAUTH_X_CLIENT_ID:oauth.x.client-id}
    client-secret: ${OAUTH_X_CLIENT_SECRET:oauth.x.client-secret}
    scope: tweet.read, users.read

  discord:
    client-id: ${OAUTH_DISCORD_CLIENT_ID:oauth.discord.client-id}
    client-secret: ${OAUTH_DISCORD_CLIENT_SECRET:oauth.discord.client-secret}
    scope: identify, email, guilds.members.read

spring.cloud.openfeign:
  client:
    config:
      default:
        logger-level: full
  compression:
    response:
      enabled: false
  httpclient:
    max-connections: 2000
    max-connections-per-route: 500

jwt:
  secret: 12345678901234567890123456789012

logging:
  level:
    devchw.oauth.client: debug

